### ISSUE TITLE
feature: kflex does not support 'list' of control planes

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubeflex#236] opened 2024-04-23 15:28 UTC
### Feature Description

I can create a cp with kflex, I can delete a cp. But if I walk into a situation where I did not create the cp with kflex, I do not have a way to list the cps quickly with kflex. I know that I can use kubectl to do this, but most users do not know this connection

### Proposed Solution

add 'list' to the operations for kubeflex

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment] 2024-04-25 05:24
Isn't this a duplicate of #159 ?

**Comment by pdettori** [comment] 2024-04-25 13:38
I agree, this is a duplicate of #159 - @clubanderson is it ok to close this one and track the issue in #159 ?

**Comment by clubanderson** [comment] 2024-04-25 15:14
it is ok to close this, so long as the priority is increased on #159

**Comment by pdettori** [comment] 2024-04-25 15:26
ok, thanks, done

**Closed by pdettori** 2024-04-25 15:26 UTC
Labels: duplicate
